import { expect, test } from "@playwright/test";

test("taxpayer proof is generated by the live MCP workflow", async ({ page }) => {
  await page.goto("/");
  await expect(page.getByRole("heading", { name: "Every number has a source." })).toBeVisible();
  await page.getByRole("button", { name: "Run synthetic MCP workflow" }).click();
  await expect(page.getByText("Ready for review", { exact: true })).toBeVisible();
  await expect(page.getByText("₹1,72,328").first()).toBeVisible();
  await expect(page.getByText(/5 MCP calls completed/)).toBeVisible();
  await expect(page.locator("#proof-id")).toContainText("SHA-256");
});

test("practitioner cockpit enforces role-aware review controls", async ({ page }) => {
  await page.goto("/practitioner.html");
  await page.getByRole("button", { name: "Load live practitioner queue" }).click();
  await expect(page.locator("#queue-status")).toContainText("3 synthetic cases");
  await expect(page.getByText("Self-approval", { exact: true })).toBeVisible();
  await expect(page.getByText("Denied", { exact: true })).toBeVisible();
  const cases = page.locator(".case-card");
  await expect(cases).toHaveCount(3);
  await expect(cases.first()).toContainText("High · 92");
  await expect(cases.first()).toContainText("blocked on taxpayer confirmation");
});

test("Trust Lab runs all controls and renders integrity evidence", async ({ page }) => {
  await page.goto("/trust-lab.html");
  await expect(page.getByRole("heading", { name: "Trust, demonstrated." })).toBeVisible();
  await page.getByRole("button", { name: "Run isolated synthetic trust suite" }).click();
  await expect(page.locator("#trust-status")).toHaveText("11/11 controls passed");
  await expect(page.locator(".claim-card")).toHaveCount(11);
  await expect(page.getByText("100% coverage").first()).toBeVisible();
  await expect(page.getByText("0 of 3 canaries leaked").first()).toBeVisible();
  await expect(page.getByText("9/9 tools constrained").first()).toBeVisible();
  await expect(page.locator("#hash-list code")).toHaveCount(4);
  await expect(page.locator("body")).not.toContainText("ABCDE1234F");
  await expect(page.locator("body")).not.toContainText("canary@example.com");
});

test("role surfaces share navigation and remain explicitly synthetic", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("link", { name: "Practitioner queue" }).click();
  await expect(page).toHaveURL(/practitioner\.html$/);
  await page.getByRole("link", { name: "Trust Lab" }).click();
  await expect(page).toHaveURL(/trust-lab\.html$/);
  await expect(page.getByText(/synthetic only/i).first()).toBeVisible();
  await expect(page.getByText(/not an OS\/container security boundary/i)).toBeVisible();
});
